# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                frontend/src/client/.*|
                backend/app/email-templates/build/.*
            )$
      - id: trailing-whitespace
        exclude: ^frontend/src/client/.*
  - repo: local
    hooks:
      - id: local-biome-check
        name: eslint check
        entry: cmd /c "cd frontend && npm run lint"
        language: system
        types: [text]
        files: ^frontend/
        pass_filenames: false

      - id: local-prettier-check
        name: prettier format
        entry: cmd /c "cd frontend && npm run format"
        language: system
        files: ^frontend/src/.*\.(ts|tsx|js|jsx)$
        pass_filenames: false

      - id: local-type-check
        name: typescript type check
        entry: cmd /c "cd frontend && pnpm type-check"
        language: system
        files: ^frontend/src/.*\.(ts|tsx)$
        pass_filenames: false

      - id: local-ruff-check
        name: ruff check
        entry: cmd /c "cd backend && uv run ruff check --force-exclude --fix"
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false

      - id: local-ruff-format
        name: ruff format
        entry: cmd /c "cd backend && uv run ruff format --force-exclude"
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false

      - id: local-mypy-check
        name: mypy type check
        entry: cmd /c "cd backend && uv run mypy ."
        language: system
        types: [python]
        files: ^backend/app/
        pass_filenames: false
